# Generated by Django 3.2 on 2022-09-21 15:01

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_name', models.CharField(max_length=30)),
                ('facebook_page', models.CharField(max_length=50, unique=True)),
                ('whats_app_number', models.CharField(max_length=10)),
                ('published_date', models.DateField()),
                ('multiplewhatsappno', jsonfield.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookLeadDataDumping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=100)),
                ('ad_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('created_time', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interested', models.CharField(blank=True, max_length=20, null=True)),
                ('is_lead_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('facebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paging.facebookpages')),
            ],
        ),
    ]
