# Generated by Django 3.2 on 2022-09-21 15:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpages',
            name='multiplewhatsappno',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
