# Generated by Django 3.2 on 2022-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpages',
            name='facebook_page',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
