# Generated by Django 3.2 on 2022-08-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0004_facebookleaddatadumping_lead_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookleaddatadumping',
            old_name='is_leat_sent',
            new_name='is_lead_sent',
        ),
    ]
