# Generated by Django 3.2 on 2022-09-21 14:16

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0005_rename_is_leat_sent_facebookleaddatadumping_is_lead_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookleaddatadumping',
            name='interested',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facebookpages',
            name='multiplewhatsappno',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
